apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  appsettings.json: |-
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
          },
          "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.NewRelic.Logs", "Serilog.Exceptions", "Serilog.Enrichers.Thread", "Serilog.Enrichers.Process", "Serilog.Enrichers.Environment", "NewRelic.LogEnrichers.Serilog" ]
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "restrictedToMinimumLevel": "Verbose",
              "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}",
              "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
            }
          },
          {
            "Name": "NewRelic",
            "Args": {
              "applicationName": "identity-api-dev",
              "licenseKey": "",
              "endpointUrl": "https://log-api.newrelic.com/log/v1",
              "restrictedToMinimumLevel": "warning"
            }
          }
        ],
        "Enrich": [
          "WithExceptionDetails",
          "FromLogContext",
          "WithMachineName",
          "WithThreadId",
          "WithNewRelicLogsInContext",
          "WithHttpRequestClientHostIP",
          "WithHttpRequestClientHostName",
          "WithHttpRequestId",
          "WithHttpRequestNumber",
          "WithHttpRequestRawUrl",
          "WithHttpRequestTraceId",
          "WithHttpRequestType",
          "WithHttpRequestUrl",
          "WithHttpRequestUrlReferrer",
          "WithHttpRequestUserAgent",
          "WithHttpSessionId",
          "WithUserName"
        ]
      },
      "AllowedHosts": "*",
      "Auth0": {
        "Domain": "",
        "ApiIdentifier": ""
      },
      "Auth0Management": {
        "Domain": "",
        "audience": "",
        "client_id": "",
        "client_secret": ""
      },
      "CartDatabaseSettings": {
        "UsersCollectionName": "",
        "ConnectionString": "",
        "DatabaseName": ""
      },
      "LaunchDarklySettings": {
        "User": "",
        "Key": ""
      }
    }

  
  
