---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}
        envFrom:
          - configMapRef: 
              name: {{ .Values.ConfigMap.name }}
          - secretRef:
              name: {{ .Values.Secret.name }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"