apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    networking.gke.io/managed-certificates: hcobian-api-dev
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: {{ .Values.name }}
      port:
        number: 443
