apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
    Auth0__Domain: ""
    Auth0Management__client_id: ""
    Auth0Management__client_secret: ""
    CartDatabaseSettings__UsersCollectionName: "User"
    CartDatabaseSettings__ConnectionString: ""
    CartDatabaseSettings__DatabaseName: "Cart"
    Serilog__WriteTo__1__Args__licenseKey : "NRII-"
    LaunchDarklySettings__User: ""
    LaunchDarklySettings__Key: ""
    