---
apiVersion: v1
kind: Service
metadata:
  name: cart-dev-api-service
  namespace: default
  labels:
    app: cart-dev-api
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: cart-dev-api
  type: LoadBalancer
  loadBalancerIP: ""
