deployment:
  image: gcr.io/PROJECT_ID/IMAGE:TAG

namespace: identity-api-dev
name: identity-api

ConfigMap:
  name: authorization-config
  data: 
    ASPNETCORE_ENVIRONMENT: Development

Secret:
  name: authorization-secrets

replicaCount: 1
