apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-authorization-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-authorization-api
  template:
    spec:
      containers:
      - name: cart-authorization-api
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

