---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-api-config-dev
data:
  ASPNETCORE_ENVIRONMENT: Development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api-dev
  template:
    metadata:
      labels:
        app: cart-api-dev
    spec:
      containers:
      - name: cart-api-dev
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        envFrom:
          - configMapRef: 
              name: cart-api-config-dev
          - secretRef:
              name: cart-api-secret-dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

