---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-dev-api-config
  namespace: default
  labels:
    app: cart-dev-api
data:
  ASPNETCORE_ENVIRONMENT: Development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-dev-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-dev-api
  template:
    metadata:
      labels:
        app: cart-dev-api
    spec:
      containers:
      - name: cart-dev-api
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        envFrom:
          - configMapRef: 
              name: cart-dev-api-config
          - secretRef:
              name: cart-dev-api-secret

        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

