apiVersion: v1
kind: Secret
metadata:
  name: cart-dev-api-secret
type: Opaque
stringData:
    Auth0__Domain: "iam.bc.dev.americommerce.cloud"
    Auth0__ApiIdentifier: "api.local"
    Auth0Management__Domain: "domain"