---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service-dev
  namespace: default
  labels:
    app: cart-api-dev
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: cart-api-dev
  type: LoadBalancer
  loadBalancerIP: ""
