apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cart-api-ns-dev
commonLabels:
  app: cart-api-dev

bases: 
- ../../base

resources:
- namespace.yaml 
- ConfigMap.yaml
- secret.yaml

patchesStrategicMerge:
- custom-deployment.yaml